# Generated by Django 3.2.4 on 2023-02-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('version', models.CharField(blank=True, max_length=128)),
                ('label', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('buyUrl', models.URLField(blank=True)),
                ('code', models.CharField(max_length=128)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
